[project]
name = "minio-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.135.2",
    "httpx>=0.28.1",
    "minio>=7.2.20",
    "uvicorn>=0.42.0",
]

[dependency-groups]
dev = []
